schema_version: 1.2.0
id: CVE-2013-2191
aliases: []
modified: 2018-10-30T16:27Z
published: 2014-02-08T00:55Z
details: python-bugzilla before 0.9.0 does not validate X.509 certificates, which
  allows man-in-the-middle attackers to spoof Bugzilla servers via a crafted certificate.
severity:
- type: CVSS_V2
  score: 4.3
affected:
- package:
    name: opensuse
    cpe: cpe:2.3:o:opensuse:opensuse
- ranges:
  - type: GIT
    repo: https://git.fedorahosted.org/cgit/python-bugzilla.git
    events:
    - introduced: '0'
    - fixed: a782282ee479ba4cc1b8b1d89700ac630ba83eef
- versions:
  - '12.3'
  - '11.4'
  - '12.2'
references:
- type: WEB
  url: https://lists.fedorahosted.org/pipermail/python-bugzilla/2013-June/000104.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-updates/2013-07/msg00026.html
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=951594
- type: WEB
  url: http://lists.opensuse.org/opensuse-updates/2013-07/msg00025.html
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2013/06/19/6
- type: FIX
  url: https://git.fedorahosted.org/cgit/python-bugzilla.git/commit/?id=a782282ee479ba4cc1b8b1d89700ac630ba83eef
