schema_version: 1.2.0
id: CVE-2021-29554
aliases:
- GHSA-qg48-85hg-mqc5
modified: 2021-05-20T16:05Z
published: 2021-05-14T19:15Z
details: TensorFlow is an end-to-end open source platform for machine learning. An
  attacker can cause a denial of service via a FPE runtime error in `tf.raw_ops.DenseCountSparseOutput`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/efff014f3b2d8ef6141da30c806faf141297eca1/tensorflow/core/kernels/count_ops.cc#L123-L127)
  computes a divisor value from user data but does not check that the result is 0
  before doing the division. Since `data` is given by the `values` argument, `num_batch_elements`
  is 0. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this
  commit on TensorFlow 2.4.2, and TensorFlow 2.3.3, as these are also affected.
severity:
- type: CVSS_V3
  score: 5.5
- type: CVSS_V2
  score: 2.1
affected:
- package:
    name: tensorflow
    cpe: cpe:2.3:a:google:tensorflow
- ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: '0'
    - fixed: da5ff2daf618591f64b2b62d9d9803951b945e9f
- database_specific:
    CWE:
    - CWE-369
    CVSS:
      Score: 5.5
      Severity: MEDIUM
      Code: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/da5ff2daf618591f64b2b62d9d9803951b945e9f
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-qg48-85hg-mqc5
